services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    build: "."
    ports:
      - 3000:3000
      - 5001:5003
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://peppermint:1234@db:5432/peppermint"
      SECRET: 'peppermint4life'
     
volumes: 
 pgdata:
